export const talentsTypes = {
  TALENT_REGISTER: "TALENT_REGISTER",
  TALENT_LOGIN: "TALENT_lOGIN",
  TALENT_LOGOUT: "TALENT_LOGOUT",
  TALENTS_GET: 'TALENTS_GET',
  TALENTS_ADD: 'TALENTS_ADD',
  TALENTS_FILTERED: 'TALENTS_FILTERED'
}